import type { Metadata } from "next";
import "./globals.css";

import { inter } from "./ui/fonts";
import NavBar from "./ui/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + "w-dvh h-screen flex flex-col"}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
